first attempt
SlipuyKamiN/Project-14 pull request #33
Opened 2022-12-24 18:31 UTC by DmytroSkoryk

2022-12-24 21:20 UTC, SlipuyKamiN requested changes

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +    padding-top: 16px;
це геть прибирай

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +    color: $text-and-modal-white;
тут додай margin-bottom: 16px замість падінга нижнього заголовка. тут в нас є два сусідні елементи <p> між ними відступи робляться тільки марджином, падінги - для внутрішніх відступів всередині елемента

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/partials/i-footer.html
> +      <div>
на цей дів вішай клас і задавай margin-bottom:60px

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +    padding-top: 60px;
цей падінг видаляєш, та сама ситуація. Зовнішні відступи (між сусідніми елементами) - марджини, внутріші вжимання контенту - падінги

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +    padding-bottom: 20px;
замість падінга - margin-bottom: 20px

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +    letter-spacing: 0.04em;
можна не задавати, успадковується від body

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +        padding-right:0;
Не бачу, на що він впливає, можливо ти хотів написати padding-right. Впринципі і на тих 2рх і тут, мали б бути марджини і там і там, тому запишеш вище margin-left:2px i тут margin-left:0

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +        padding-bottom: 34px;
i top i bottom - марджини

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +        line-height: 1,86;
опечатка, просто постав крапку, замість коми --> 1.86

2022-12-24 21:20 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +        font-size: 14px;
в десктопі font-size: 16px, треба додати медіаправило

2022-12-24 21:39 UTC, DmytroSkoryk commented on src/sass/layouts/_i-footer.scss
> +    letter-spacing: 0.04em;
успадковується font-weight: 400

2022-12-25 00:38 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +    letter-spacing: 0.04em;
я маю на увазі letter-spacing успадковується

2022-12-25 02:55 UTC, SlipuyKamiN requested changes

2022-12-25 02:55 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +        padding-top: 14px;
цей падінг можеш прибирати, він вже не потрібен

2022-12-25 02:55 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +        padding-top: 0;
цей падінг можеш прибирати, він вже не потрібен

2022-12-25 02:55 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +    @media screen and (min-width: 1200px) {
тут теж треба margin-bottom: 14px;

2022-12-25 02:55 UTC, SlipuyKamiN commented on src/sass/layouts/_i-footer.scss
> +    margin-bottom:60px;
тут додай медіаправило, він потрібен тільки для мобілки

2022-12-25 09:16 UTC, SlipuyKamiN approved these changes

2022-12-25 09:16 UTC, merged